name: Actions ðŸ˜Ž

on: [push, pull_request]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    name: Build my project âœ¨
    runs-on: ubuntu-22.04
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Tests
      - name: Run tests
        id: tests
        uses: game-ci/unity-test-runner@v4
        continue-on-error: true
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          unityVersion: 6000.2.8f1
          projectPath: "Unity Files"
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL}}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      # Build
      - name: Build project
        id: build
        uses: game-ci/unity-builder@v4
        continue-on-error: true
        with:
          unityVersion: 6000.2.8f1
          targetPlatform: WebGL
          projectPath: "Unity Files"
          allowDirtyBuild: true
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL}}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      # Output
      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build
