name: Actions ðŸ˜Ž

on: [push, pull_request]

jobs:
  build:
    name: Build my project âœ¨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      
      - name: Debugging env (will remove later)
        run: |
          echo "UNITY_LICENSE length: ${#UNITY_LICENSE}"
        shell: bash
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          unityVersion: 6000.2.8f1
          projectPath: "Unity Files"
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL}}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      
      - name: Build project
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 6000.2.8f1
          targetPlatform: WebGL
          projectPath: "Unity Files"
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL}}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      # Output
      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build
