name: Unity CI

on: [push, pull_request]

permissions:
  contents: read
  checks: write
  pull-requests: write

# generally how this works is:
# cache checks for library files
# if C# & scripts are different -> rebuild library files -> cache them
# after caching is complete, pass on to linting & testing
# linting takes from cache, compiles project in unity to make a .sln file to then check the C# code
# testing takes from cache, compiles project in unity to run the unit test format that unity itself provides
# if tests pass -> build & compile code into .exe in the build job

# if caching fails -> a memory or unity crash problem; needs re-run or manual review
# if linting fails -> usually formatting problems; will auto fix
# if testing fails -> code needs fixing / tests need re-evaluation; manual review
# if building fails -> compiler errors; review C# scripts for errors

jobs:

  # setup and use from https://github.com/docker/build-push-action/issues/225
  setup:
    name: Docker Setup
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # this was taken from https://github.com/marketplace/actions/free-disk-space-ubuntu, which
      # was found from https://game.ci/docs/troubleshooting/common-issues/#no-space-left-on-device
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
          
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          # letting dotnet stay on all instances since we use C#
          # if for some reason we need 4GB more, re-eval this
          dotnet: false
          haskell: true
          large-packages: true
          # maybe this will fix build & push issues
          docker-images: false
          swap-storage: true

      - name: List directory (debug)
        run: |
          ls -R .

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          #context: .
          file: ./Dockerfile
          tags: myimage:latest
          outputs: type=docker,dest=/tmp/myimage.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: myimage
          path: /tmp/myimage.tar

  cache:
    name: Compile Library Folder
    runs-on: ubuntu-22.04
    needs: setup
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: myimage
          path: /tmp
    
      - name: Load Docker image
        run: |
          docker load --input /tmp/myimage.tar
          docker image ls -a

      # checkout
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          lfs: true

      # cache
      - name: Check cache for files
        id: unity-cache
        uses: actions/cache@v3
        with:
          path: Unity Files/Library
          key: Library-${{ hashFiles('Unity Files/Assets/**', 'Unity Files/Packages/**', 'Unity Files/ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Check cache status
        run: |
          if [ "${{ steps.unity-cache.outputs.cache-hit }}" = "true" ]; then
            echo "Cache found - skipping Library rebuild"
          else
            echo "No cache - rebuilding Library"
          fi

      # # this was taken from https://github.com/marketplace/actions/free-disk-space-ubuntu, which
      # # was found from https://game.ci/docs/troubleshooting/common-issues/#no-space-left-on-device
      # - name: Free Disk Space (Ubuntu)
      #   if: steps.unity-cache.outputs.cache-hit != 'true'
      #   uses: jlumbroso/free-disk-space@main
      #   with:
      #     # this might remove tools that are actually needed,
      #     # if set to "true" but frees about 6 GB
      #     tool-cache: false
          
      #     # all of these default to true, but feel free to set to
      #     # "false" if necessary for your workflow
      #     android: true
      #     # letting dotnet stay on all instances since we use C#
      #     # if for some reason we need 4GB more, re-eval this
      #     dotnet: false
      #     haskell: true
      #     large-packages: true
      #     docker-images: true
      #     swap-storage: true
      
      - name: Setup Unity Library folder
        if: steps.unity-cache.outputs.cache-hit != 'true'
        continue-on-error: true
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 6000.2.8f1
          targetPlatform: StandaloneWindows64
          projectPath: "Unity Files"
          allowDirtyBuild: true
          customImage: unityci/editor:ubuntu-6000.2.8f1-windows-mono-3
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          TMPDIR: /tmp

  test:
    name: Run Unity Tests
    runs-on: ubuntu-22.04
    needs: cache
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: myimage
          path: /tmp
    
      - name: Load Docker image
        run: |
          docker load --input /tmp/myimage.tar
          docker image ls -a

      # - name: Free Disk Space (Ubuntu)
      #   uses: jlumbroso/free-disk-space@main
      #   with:
      #     tool-cache: false
          
      #     android: true
      #     dotnet: false
      #     haskell: true
      #     large-packages: true
      #     docker-images: true
      #     swap-storage: true
  
      # checkout
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          lfs: true

      # cache
      - name: Check cache for files
        uses: actions/cache@v3
        with:
          path: Unity Files/Library
          key: Library-${{ hashFiles('Unity Files/Assets/**', 'Unity Files/Packages/**', 'Unity Files/ProjectSettings/**') }}
          restore-keys: |
            Library-

      # test
      - name: Run PlayMode tests
        id: tests
        uses: game-ci/unity-test-runner@v4
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          unityVersion: 6000.2.8f1
          projectPath: "Unity Files"
          customImage: unityci/editor:ubuntu-6000.2.8f1-windows-mono-3
          # PlayMode is what runs it as the actual game, otherwise EditorMode is for logic checking
          testMode: PlayMode
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL}}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          TMPDIR: /tmp

  build:
    name: Build Unity Project
    runs-on: ubuntu-22.04
    needs: test
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: myimage
          path: /tmp
    
      - name: Load Docker image
        run: |
          docker load --input /tmp/myimage.tar
          docker image ls -a

      # - name: Free Disk Space (Ubuntu)
      #   uses: jlumbroso/free-disk-space@main
      #   with:
      #     tool-cache: false
          
      #     android: true
      #     dotnet: false
      #     haskell: true
      #     large-packages: true
      #     docker-images: true
      #     swap-storage: true

      # checkout
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          lfs: true

      # cache
      - name: Check cache for files
        uses: actions/cache@v3
        with:
          path: Unity Files/Library
          key: Library-${{ hashFiles('Unity Files/Assets/**', 'Unity Files/Packages/**', 'Unity Files/ProjectSettings/**') }}
          restore-keys: |
            Library-

      # build
      - name: Build project
        id: build
        uses: game-ci/unity-builder@v4
        # continue-on-error: true
        with:
          unityVersion: 6000.2.8f1
          targetPlatform: StandaloneWindows64
          projectPath: "Unity Files"
          allowDirtyBuild: true
          customImage: unityci/editor:ubuntu-6000.2.8f1-windows-mono-3
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL}}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          BUILD_NAME: SamuRat
          BUILD_PATH: build/SamuRat
          BUILD_FILE: SamuRat.exe
          TMPDIR: /tmp

      # output compiled build
      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build

  # linter
  lint:
    name: Lint C# Code
    runs-on: ubuntu-22.04
    needs: cache
    permissions:
      contents: write # to commit the linting changes
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: myimage
          path: /tmp
    
      - name: Load Docker image
        run: |
          docker load --input /tmp/myimage.tar
          docker image ls -a

      # - name: Free Disk Space (Ubuntu)
      #   uses: jlumbroso/free-disk-space@main
      #   with:
      #     tool-cache: false

      #     # docker images & dotnet false for the dotnet install & commands
      #     android: true
      #     dotnet: false
      #     haskell: true
      #     large-packages: true
      #     docker-images: false
      #     swap-storage: true

      # checkout
      - name: Checkout repository
        uses: actions/checkout@v5

      # cache
      - name: Check cache for files
        uses: actions/cache@v3
        with:
          path: Unity Files/Library
          key: Library-${{ hashFiles('Unity Files/Assets/**', 'Unity Files/Packages/**', 'Unity Files/ProjectSettings/**') }}
          restore-keys: |
            Library-

      # unity setup & sln file
      - name: Setup Unity & generate sln
        continue-on-error: true
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 6000.2.8f1
          projectPath: "Unity Files"
          buildMethod: Packages.Rider.Editor.RiderScriptEditor.SyncSolution
          customImage: unityci/editor:ubuntu-6000.2.8f1-windows-mono-3
          targetPlatform: StandaloneWindows64
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL}}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          TMPDIR: /tmp

      - name: Install dotnet-format
        run: dotnet tool install --global dotnet-format

      - name: Add dotnet tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: List files to double check
        run: ls -R "Unity Files"

      - name: Run dotnet-format linter
        run: |
          dotnet-format "Unity Files/Unity Files.sln"

      - name: Configure git for commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit formatted code
        run: |
          git add .
          git commit -m "Apply dotnet-format fixes" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

