name: Unity CI

on: [push, pull_request]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    name: Run Unity Tests
    runs-on: ubuntu-22.04
    steps:
  
      # checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # cache
      - name: Cache
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # test
      - name: Run PlayMode tests
        id: tests
        uses: game-ci/unity-test-runner@v4
        # commenting this out as it seems to not crash anymore?
        # continue-on-error: true
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          unityVersion: 6000.2.8f1
          projectPath: "Unity Files"
          customImage: unityci/editor:ubuntu-6000.2.8f1-windows-mono-3
          testMode: PlayMode
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL}}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          TMPDIR: /tmp

      # help with memory / segfault issues
      - name: Clean up docker space
        run: |
          echo "Removing unused docker images and containers..."
          docker system prune -af
        env:
          TMPDIR: /tmp

  build:
    name: Build Unity Project
    runs-on: ubuntu-22.04
    needs: test
    steps:

      # checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # build
      - name: Build project
        id: build
        uses: game-ci/unity-builder@v4
        # continue-on-error: true
        with:
          unityVersion: 6000.2.8f1
          targetPlatform: StandaloneWindows64
          projectPath: "Unity Files"
          allowDirtyBuild: true
          customImage: unityci/editor:ubuntu-6000.2.8f1-windows-mono-3
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL}}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          BUILD_NAME: SamuRat
          BUILD_PATH: build/SamuRat
          BUILD_FILE: SamuRat.exe
          TMPDIR: /tmp

      # output compiled build
      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build

  # linter
  lint:
    name: Lint C# Code
    runs-on: ubuntu-22.04
    steps:

      # checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # unity setup
      - name: Setup Unity for sln generation
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 6000.2.8f1
          targetPlatform: StandaloneWindows64
          projectPath: "Unity Files"
          allowDirtyBuild: true
          customImage: unityci/editor:ubuntu-6000.2.8f1-windows-mono-3
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL}}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          TMPDIR: /tmp

      # generating the .sln
      - name: Generate Unity C# sln
        run: |
          $UNITY_EXECUTABLE -batchmode -quit -projectPath "Unity Files" -executeMethod UnityEditor.SyncVS.SyncSolution
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Install dotnet-format
        run: dotnet tool install --global dotnet-format

      - name: Add dotnet tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Run dotnet-format linter
        run: |
          dotnet-format --check "Unity Files/Unity Files.sln"
